# Generated by Django 5.0.2 on 2024-02-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NovoTaskNinja', '0003_cycrequirement_alter_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inprogresscourse',
            name='days_of_week',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='inprogresscourse',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inprogresscourse',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
