# Generated by Django 5.0.2 on 2024-02-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NovoTaskNinja', '0004_inprogresscourse_days_of_week_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='foodDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_lethal', models.BooleanField(default=False)),
            ],
        ),
    ]
